name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: true

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@2a2412009026a83f51d179f92dc2b3fd4c8142df # v1.4.1
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build JAR
        shell: bash
        # language=bash
        run: |
          ./mvnw --no-transfer-progress --batch-mode --also-make --projects cli package 

      - name: Upload JAR
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: kafka-streams-topology-viz-cli
          path: cli/target/kafka-streams-topology-viz-*.jar
          retention-days: 1
          if-no-files-found: error

  build-native:
    needs: [ build-jar ]
    name: Build Native Image (${{ matrix.os }}-${{ matrix.arch }})
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-24.04
            os_name: linux
            arch: x86_64
          - os: ubuntu-24.04-arm
            os_name: linux
            arch: aarch_64
          # macOS builds
          - os: macos-15
            os_name: osx
            arch: aarch_64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download CLI artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: kafka-streams-topology-viz-cli
          path: cli/target/

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@2a2412009026a83f51d179f92dc2b3fd4c8142df # v1.4.1
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image (${{ matrix.os_name }}-${{ matrix.arch }})
        # language=bash
        run: |
          export GRAALVM_HOME=$JAVA_HOME
          ./mvnw --no-transfer-progress --batch-mode --also-make --projects cli --activate-profiles native package 

      - name: Upload Native Image
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: native-image-${{ matrix.os_name }}-${{ matrix.arch }}
          path: cli/target/kafka-streams-topology-viz-${{ matrix.os_name }}-${{ matrix.arch }}-*
          retention-days: 1
          if-no-files-found: error

  release:
    name: Create Release
    needs: [ build-jar, build-native ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Download native artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: native-image-*
          path: cli/target/
          merge-multiple: true

      - name: Download CLI artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: kafka-streams-topology-viz-cli
          path: cli/target/

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@2a2412009026a83f51d179f92dc2b3fd4c8142df # v1.4.1
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        # language=bash
        run: |
          ./mvnw --no-transfer-progress --batch-mode --also-make --projects lib --activate-profiles publication

      - name: Show staged artifacts for Maven Central
        shell: bash
        # language=bash
        run: |
          set -x
          ls -laR target/staging-deploy/
          ls -laR cli/target

      - name: Run JReleaser
        shell: bash
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        # language=bash
        run: |
          # Run JReleaser full-release (includes GitHub release and Maven Central deployment)
          ./mvnw --no-transfer-progress --batch-mode jreleaser:full-release

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jreleaser-logs
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties
